CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE drug_profiles (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    trade_name          VARCHAR(255),
    inn                 VARCHAR(255),
    dosage              VARCHAR(100),
    manufacturer        VARCHAR(255),

    dosage_form         VARCHAR(50),
    shape               VARCHAR(50),
    profile             VARCHAR(50),
    color_primary       VARCHAR(50),
    color_secondary     VARCHAR(50),
    color_notes         TEXT,
    surface             VARCHAR(50),
    coating             VARCHAR(50),
    translucency        VARCHAR(50),

    capsule_type        VARCHAR(20),
    capsule_size        VARCHAR(5),
    capsule_body_color  VARCHAR(50),
    capsule_cap_color   VARCHAR(50),
    contents_color      VARCHAR(50),
    contents_type       VARCHAR(50),

    imprint_present     BOOLEAN DEFAULT FALSE,
    imprint_text        VARCHAR(255),
    imprint_color       VARCHAR(50),
    imprint_side        VARCHAR(20),
    logo_or_symbol      VARCHAR(255),

    has_score_line      BOOLEAN DEFAULT FALSE,
    score_line_count    INTEGER,
    score_line_side     VARCHAR(20),

    free_description    TEXT,
    source              VARCHAR(20),
    original_text       TEXT,
    raw_model_output    JSONB,
    embedding           vector(1536),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_drug_profiles_embedding
    ON drug_profiles
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE qc_checks (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reference_profile_id UUID REFERENCES drug_profiles(id),
    image_path           TEXT,
    extracted_json       JSONB,
    match_score          NUMERIC(4,3),
    passed               BOOLEAN,
    fail_reasons         TEXT,
    model_name           VARCHAR(100),
    checked_at           TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO drug_profiles (
    trade_name, inn, dosage, manufacturer,
    dosage_form, shape, profile,
    color_primary, color_secondary, color_notes,
    surface, coating, translucency,
    capsule_type, capsule_size, capsule_body_color, capsule_cap_color,
    contents_color, contents_type,
    imprint_present, imprint_text, imprint_color, imprint_side, logo_or_symbol,
    has_score_line, score_line_count, score_line_side,
    free_description, source, original_text, raw_model_output
) VALUES
(
    'Нурофен', NULL, NULL, NULL,
    'soft_capsule', 'oval', NULL,
    'red', NULL, 'красная полупрозрачная желатиновая оболочка',
    'smooth', 'none', 'translucent',
    'soft', NULL, NULL, NULL,
    'transparent', 'liquid',
    TRUE, 'NUROFEN', 'white', NULL, NULL,
    FALSE, NULL, NULL,
    'Капсулы мягкие овальные с красной полупрозрачной желатиновой оболочкой, с идентифицирующей надписью белого цвета "NUROFEN", содержащие прозрачную жидкость от бесцветного до светло-розового цвета.',
    'json',
    'Капсулы мягкие овальные с красной полупрозрачной желатиновой оболочкой, с идентифицирующей надписью белого цвета "NUROFEN", содержащие прозрачную жидкость от бесцветного до светло-розового цвета.',
    '{
      "drug_name": "Нурофен",
      "dosage_form": "soft_capsule",
      "shape": "oval",
      "profile": null,
      "color_primary": "red",
      "color_secondary": null,
      "color_notes": "красная полупрозрачная желатиновая оболочка",
      "surface": "smooth",
      "coating": "none",
      "translucency": "translucent",
      "capsule_type": "soft",
      "capsule_size": null,
      "capsule_body_color": null,
      "capsule_cap_color": null,
      "contents_color": "transparent",
      "contents_type": "liquid",
      "imprint_present": true,
      "imprint_text": "NUROFEN",
      "imprint_color": "white",
      "imprint_side": null,
      "logo_or_symbol": null,
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Капсулы мягкие овальные с красной полупрозрачной желатиновой оболочкой, с идентифицирующей надписью белого цвета \"NUROFEN\", содержащие прозрачную жидкость от бесцветного до светло-розового цвета."
    }'::jsonb
),
(
    'Ксарелто', NULL, NULL, NULL,
    'film_tablet', 'round', 'biconvex',
    'pink', NULL, NULL,
    NULL, 'film', NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL,
    TRUE, '10', 'other', 'both', 'triangle; фирменный байеровский крест',
    FALSE, NULL, NULL,
    'Таблетки, покрытые пленочной оболочкой розового цвета, круглые, двояковыпуклые; методом выдавливания нанесена гравировка: на одной стороне - треугольник с обозначением дозировки "10", на другой - фирменный байеровский крест.',
    'json',
    'Таблетки, покрытые пленочной оболочкой розового цвета, круглые, двояковыпуклые; методом выдавливания нанесена гравировка: на одной стороне - треугольник с обозначением дозировки "10", на другой - фирменный байеровский крест.',
    '{
      "drug_name": "Ксарелто",
      "dosage_form": "film_tablet",
      "shape": "round",
      "profile": "biconvex",
      "color_primary": "pink",
      "color_secondary": null,
      "color_notes": null,
      "surface": null,
      "coating": "film",
      "translucency": null,
      "capsule_type": null,
      "capsule_size": null,
      "capsule_body_color": null,
      "capsule_cap_color": null,
      "contents_color": null,
      "contents_type": null,
      "imprint_present": true,
      "imprint_text": "10",
      "imprint_color": "other",
      "imprint_side": "both",
      "logo_or_symbol": "triangle; фирменный байеровский крест",
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Таблетки, покрытые пленочной оболочкой розового цвета, круглые, двояковыпуклые; методом выдавливания нанесена гравировка: на одной стороне - треугольник с обозначением дозировки \"10\", на другой - фирменный байеровский крест."
    }'::jsonb
),
(
    'Форсига', NULL, NULL, NULL,
    'film_tablet', 'round', 'biconvex',
    'yellow', NULL, NULL,
    NULL, 'film', NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL,
    TRUE, '5; 1427', 'other', 'both', NULL,
    FALSE, NULL, NULL,
    'Таблетки, покрытые пленочной оболочкой желтого цвета, круглые, двояковыпуклые, с гравировкой "5" на одной стороне и "1427" на другой стороне.',
    'json',
    'Таблетки, покрытые пленочной оболочкой желтого цвета, круглые, двояковыпуклые, с гравировкой "5" на одной стороне и "1427" на другой стороне.',
    '{
      "drug_name": "Форсига",
      "dosage_form": "film_tablet",
      "shape": "round",
      "profile": "biconvex",
      "color_primary": "yellow",
      "color_secondary": null,
      "color_notes": null,
      "surface": null,
      "coating": "film",
      "translucency": null,
      "capsule_type": null,
      "capsule_size": null,
      "capsule_body_color": null,
      "capsule_cap_color": null,
      "contents_color": null,
      "contents_type": null,
      "imprint_present": true,
      "imprint_text": "5; 1427",
      "imprint_color": "other",
      "imprint_side": "both",
      "logo_or_symbol": null,
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Таблетки, покрытые пленочной оболочкой желтого цвета, круглые, двояковыпуклые, с гравировкой \"5\" на одной стороне и \"1427\" на другой стороне."
    }'::jsonb
),
(
    'Эдарби', NULL, NULL, NULL,
    'tablet', 'round', 'biconvex',
    'white', NULL, 'от белого до почти белого цвета',
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL,
    TRUE, 'ASL; 20', 'other', 'both', NULL,
    FALSE, NULL, NULL,
    'Таблетки от белого до почти белого цвета, круглые, двояковыпуклые, с гравировкой "ASL" на одной стороне и "20" на другой.',
    'json',
    'Таблетки от белого до почти белого цвета, круглые, двояковыпуклые, с гравировкой "ASL" на одной стороне и "20" на другой.',
    '{
      "drug_name": "Эдарби",
      "dosage_form": "tablet",
      "shape": "round",
      "profile": "biconvex",
      "color_primary": "white",
      "color_secondary": null,
      "color_notes": "от белого до почти белого цвета",
      "surface": null,
      "coating": null,
      "translucency": null,
      "capsule_type": null,
      "capsule_size": null,
      "capsule_body_color": null,
      "capsule_cap_color": null,
      "contents_color": null,
      "contents_type": null,
      "imprint_present": true,
      "imprint_text": "ASL; 20",
      "imprint_color": "other",
      "imprint_side": "both",
      "logo_or_symbol": null,
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Таблетки от белого до почти белого цвета, круглые, двояковыпуклые, с гравировкой \"ASL\" на одной стороне и \"20\" на другой."
    }'::jsonb
),
(
    'Эликвис', NULL, NULL, NULL,
    'film_tablet', 'round', NULL,
    'yellow', NULL, NULL,
    NULL, 'film', NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL,
    TRUE, '893; 2 1/2', 'other', 'both', NULL,
    FALSE, NULL, NULL,
    'Таблетки, покрытые пленочной оболочкой желтого цвета, круглые, с гравировкой "893" на одной стороне и "2 1/2" на другой стороне.',
    'json',
    'Таблетки, покрытые пленочной оболочкой желтого цвета, круглые, с гравировкой "893" на одной стороне и "2 1/2" на другой стороне.',
    '{
      "drug_name": "Эликвис",
      "dosage_form": "film_tablet",
      "shape": "round",
      "profile": null,
      "color_primary": "yellow",
      "color_secondary": null,
      "color_notes": null,
      "surface": null,
      "coating": "film",
      "translucency": null,
      "capsule_type": null,
      "capsule_size": null,
      "capsule_body_color": null,
      "capsule_cap_color": null,
      "contents_color": null,
      "contents_type": null,
      "imprint_present": true,
      "imprint_text": "893; 2 1/2",
      "imprint_color": "other",
      "imprint_side": "both",
      "logo_or_symbol": null,
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Таблетки, покрытые пленочной оболочкой желтого цвета, круглые, с гравировкой \"893\" на одной стороне и \"2 1/2\" на другой стороне."
    }'::jsonb
),
(
    'Ингавирин', NULL, NULL, NULL,
    'hard_capsule', 'capsule_shaped', NULL,
    'red', NULL, 'содержимое белого или почти белого цвета',
    NULL, NULL, NULL,
    NULL, NULL, 'red', 'red',
    'white', 'granules',
    TRUE, 'И', 'white', NULL, 'кольцо и буква "И" внутри кольца',
    FALSE, NULL, NULL,
    'Капсулы размера №2 или №3 красного цвета; на крышечке логотип белого цвета в виде кольца и буквы "И" внутри кольца; содержимое — гранулы и порошок белого или почти белого цвета, возможны легко рассыпающиеся конгломераты.',
    'json',
    'Капсулы размер №2 или №3, красного цвета; на крышечке капсулы нанесен логотип белого цвета в виде кольца и буквы "И" внутри кольца; содержимое капсул - гранулы и порошок белого или почти белого цвета; допускается образование конгломератов, легко рассыпающихся при легком надавливании.',
    '{
      "drug_name": "Ингавирин",
      "dosage_form": "hard_capsule",
      "shape": "capsule_shaped",
      "profile": null,
      "color_primary": "red",
      "color_secondary": null,
      "color_notes": "содержимое белого или почти белого цвета",
      "surface": null,
      "coating": null,
      "translucency": null,
      "capsule_type": null,
      "capsule_size": null,
      "capsule_body_color": "red",
      "capsule_cap_color": "red",
      "contents_color": "white",
      "contents_type": "granules",
      "imprint_present": true,
      "imprint_text": "И",
      "imprint_color": "white",
      "imprint_side": null,
      "logo_or_symbol": "кольцо и буква \"И\" внутри кольца",
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Капсулы размера №2 или №3 красного цвета; на крышечке логотип белого цвета в виде кольца и буквы \"И\" внутри кольца; содержимое — гранулы и порошок белого или почти белого цвета, возможны легко рассыпающиеся конгломераты."
    }'::jsonb
),
(
    'Урсосан', NULL, NULL, NULL,
    'hard_capsule', 'capsule_shaped', NULL,
    'white', NULL, 'почти белый',
    NULL, NULL, 'opaque',
    'hard', '0', 'white', 'white',
    'white', 'powder',
    FALSE, NULL, NULL, NULL, NULL,
    FALSE, NULL, NULL,
    'Твердые желатиновые капсулы размера №0, белые, непрозрачные; содержимое — белый или почти белый порошок, местами с кусочками массы или спрессованный, распадающийся при надавливании.',
    'json',
    'Капсулы твердые желатиновые, размер №0, белого цвета, непрозрачные; содержимое капсул - белый или почти белый порошок, либо белый или почти белый порошок с кусочками массы, либо белый или почти белый спрессованный порошок, распадающийся при надавливании.',
    '{
      "drug_name": "Урсосан",
      "dosage_form": "hard_capsule",
      "shape": "capsule_shaped",
      "profile": null,
      "color_primary": "white",
      "color_secondary": null,
      "color_notes": "почти белый",
      "surface": null,
      "coating": null,
      "translucency": "opaque",
      "capsule_type": "hard",
      "capsule_size": "0",
      "capsule_body_color": "white",
      "capsule_cap_color": "white",
      "contents_color": "white",
      "contents_type": "powder",
      "imprint_present": false,
      "imprint_text": null,
      "imprint_color": null,
      "imprint_side": null,
      "logo_or_symbol": null,
      "has_score_line": false,
      "score_line_count": null,
      "score_line_side": null,
      "free_description": "Твердые желатиновые капсулы размера №0, белые, непрозрачные; содержимое — белый или почти белый порошок, местами с кусочками массы или спрессованный, распадающийся при надавливании."
    }'::jsonb
);